Repository ThreeMammals/Ocelot, pull requests merged in 2023-09, with the labels that each got.

#1211 Exception mapper naming
  src/Ocelot/DependencyInjection/OcelotBuilder.cs
  src/Ocelot/Requester/HttpExceptionToErrorMapper.cs
  test/Ocelot.UnitTests/Requester/HttpExceptionToErrorMapperTests.cs
Labels: bug, accepted

#1279 #908 Quality of Service - Configuration
  src/Ocelot.Provider.Polly/Interfaces/IPollyQoSProvider.cs
  src/Ocelot.Provider.Polly/OcelotBuilderExtensions.cs
  src/Ocelot.Provider.Polly/PollyCircuitBreakingDelegatingHandler.cs
  src/Ocelot.Provider.Polly/PollyQoSProvider.cs
  test/Ocelot.AcceptanceTests/PollyQoSTests.cs
  test/Ocelot.UnitTests/Polly/OcelotBuilderExtensionsTests.cs
  test/Ocelot.UnitTests/Polly/PollyCircuitBreakingDelegatingHandlerTests.cs
  test/Ocelot.UnitTests/Polly/PollyQoSProviderTests.cs
Labels: bug, accepted

#1315 Fixed logger message typos in the OutputCacheMiddleware class
  src/Ocelot/Cache/Middleware/OutputCacheMiddleware.cs
Labels: bug, accepted, documentation

#1639 fix: minor grammar fix in default rate limit response message
  src/Ocelot/RateLimit/Middleware/ClientRateLimitMiddleware.cs
Labels: accepted

#1335 #1288 Query string char missing
  src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
  test/Ocelot.AcceptanceTests/RoutingWithQueryStringTests.cs
  test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs
Labels: bug, accepted

#1366 #1057 #1068 Add service discovery logs
  src/Ocelot.Provider.Consul/Consul.cs
Labels: proposal, accepted, Service Discovery

#1367 #893 Problems to cancel a request (CancellationToken)
  src/Ocelot/Multiplexer/MultiplexingMiddleware.cs
  test/Ocelot.AcceptanceTests/CancelRequestTests.cs
  test/Ocelot.AcceptanceTests/Steps.cs
Labels: bug, accepted

#1569 #1228 #1235 #1247 Overloaded AddOcelot method for dynamic FileConfiguration construction
  src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs
  test/Ocelot.AcceptanceTests/ConfigurationReloadTests.cs
  test/Ocelot.UnitTests/DependencyInjection/ConfigurationBuilderExtensionsTests.cs
Labels: enhancement, accepted

#1655 #1351 #1510 New AddOcelot extensions to support custom ASP.NET MVC pipeline building via the IMvcCoreBuilder interface
  docs/features/administration.rst
  docs/features/configuration.rst
  docs/features/dependencyinjection.rst
  docs/features/qualityofservice.rst
  docs/features/requestaggregation.rst
  docs/features/tracing.rst
  docs/index.rst
  docs/introduction/gettingstarted.rst
  src/Ocelot/DependencyInjection/OcelotBuilder.cs
  src/Ocelot/DependencyInjection/ServiceCollectionExtensions.cs
  test/Ocelot.IntegrationTests/AdministrationTests.cs
  test/Ocelot.UnitTests/DependencyInjection/OcelotBuilderTests.cs
  test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
  test/Ocelot.UnitTests/UnitTests.runsettings
Labels: enhancement, accepted

#1678 #1677 #1686 United documentation update
  README.md
  docs/building/building.rst
  docs/features/authentication.rst
  docs/features/authorization.rst
  docs/features/caching.rst
  docs/features/claimstransformation.rst
  docs/features/configuration.rst
  docs/features/errorcodes.rst
  docs/features/headerstransformation.rst
  docs/features/loadbalancer.rst
  docs/features/logging.rst
  docs/features/methodtransformation.rst
  docs/features/middlewareinjection.rst
  docs/features/requestaggregation.rst
  docs/features/routing.rst
  docs/features/servicediscovery.rst
  docs/features/websockets.rst
  docs/introduction/bigpicture.rst
  docs/introduction/gettingstarted.rst
  src/Ocelot/RateLimit/Middleware/ClientRateLimitMiddleware.cs
Labels: accepted, documentation

#1703 #1700 Create custom Ocelot config file when instantiating steps during parallel execution
  test/Ocelot.AcceptanceTests/ConfigurationReloadTests.cs
  test/Ocelot.AcceptanceTests/CustomMiddlewareTests.cs
  test/Ocelot.AcceptanceTests/RandomPortFinder.cs
  test/Ocelot.AcceptanceTests/Steps.cs
Labels: bug, accepted

#1705 #1700 Add sequential tests with disabled parallelization
  test/Ocelot.AcceptanceTests/ConfigurationReloadTests.cs
  test/Ocelot.AcceptanceTests/SequentialTests.cs
Labels: bug

#1377 #1375 #1237 #925 #920 Fix DownstreamRoute DangerousAcceptAnyServerCertificateValidator
  src/Ocelot/DependencyInjection/OcelotBuilder.cs
  src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs
  src/Ocelot/Middleware/OcelotPipelineExtensions.cs
  src/Ocelot/WebSockets/ClientWebSocketOptionsProxy.cs
  src/Ocelot/WebSockets/ClientWebSocketProxy.cs
  src/Ocelot/WebSockets/IClientWebSocket.cs
  src/Ocelot/WebSockets/IClientWebSocketOptions.cs
  src/Ocelot/WebSockets/IWebSocketsFactory.cs
  src/Ocelot/WebSockets/WebSocketsFactory.cs
  src/Ocelot/WebSockets/WebSocketsProxyMiddleware.cs
  src/Ocelot/WebSockets/WebSocketsProxyMiddlewareExtensions.cs
  test/Ocelot.AcceptanceTests/ConsulWebSocketTests.cs
  test/Ocelot.AcceptanceTests/WebSocketTests.cs
  test/Ocelot.UnitTests/Middleware/OcelotPipelineExtensionsTests.cs
  test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
  test/Ocelot.UnitTests/WebSockets/MockWebSocket.cs
  test/Ocelot.UnitTests/WebSockets/WebSocketsProxyMiddlewareTests.cs
Labels: bug, needs feedback, websockets

#1656 #1225 Update ServiceDiscovery documentation and samples to include Custom Providers
  Ocelot.sln
  docs/features/servicediscovery.rst
  samples/OcelotServiceDiscovery/.dockerignore
  samples/OcelotServiceDiscovery/ApiGateway/Ocelot.Samples.ServiceDiscovery.ApiGateway.csproj
  samples/OcelotServiceDiscovery/ApiGateway/Program.cs
  samples/OcelotServiceDiscovery/ApiGateway/Properties/launchSettings.json
  samples/OcelotServiceDiscovery/ApiGateway/ServiceDiscovery/MyServiceDiscoveryProvider.cs
  samples/OcelotServiceDiscovery/ApiGateway/ServiceDiscovery/MyServiceDiscoveryProviderFactory.cs
  samples/OcelotServiceDiscovery/ApiGateway/appsettings.json
  samples/OcelotServiceDiscovery/ApiGateway/ocelot.json
  samples/OcelotServiceDiscovery/DownstreamService/.dockerignore
  samples/OcelotServiceDiscovery/DownstreamService/Controllers/CategoriesController.cs
  samples/OcelotServiceDiscovery/DownstreamService/Controllers/HealthController.cs
  samples/OcelotServiceDiscovery/DownstreamService/Controllers/WeatherForecastController.cs
  samples/OcelotServiceDiscovery/DownstreamService/Dockerfile
  samples/OcelotServiceDiscovery/DownstreamService/Models/HealthResult.cs
  samples/OcelotServiceDiscovery/DownstreamService/Models/MicroserviceResult.cs
  samples/OcelotServiceDiscovery/DownstreamService/Models/ReadyResult.cs
  samples/OcelotServiceDiscovery/DownstreamService/Models/WeatherForecast.cs
  samples/OcelotServiceDiscovery/DownstreamService/Ocelot.Samples.ServiceDiscovery.DownstreamService.csproj
  samples/OcelotServiceDiscovery/DownstreamService/Program.cs
  samples/OcelotServiceDiscovery/DownstreamService/Properties/launchSettings.json
  samples/OcelotServiceDiscovery/DownstreamService/Startup.cs
  samples/OcelotServiceDiscovery/DownstreamService/appsettings.Development.json
  samples/OcelotServiceDiscovery/DownstreamService/appsettings.json
  samples/OcelotServiceDiscovery/Ocelot.Samples.ServiceDiscovery.sln
  samples/OcelotServiceDiscovery/README.md
Labels: proposal, accepted, documentation

#1689 #1509 #1683 Replace non-WS protocols for the 'ClientWebSocket' in WebSocketsProxyMiddleware
  src/Ocelot/WebSockets/WebSocketsProxyMiddleware.cs
  test/Ocelot.UnitTests/WebSockets/MockWebSocket.cs
  test/Ocelot.UnitTests/WebSockets/WebSocketsProxyMiddlewareTests.cs
Labels: bug, accepted, websockets

#1670 #1634 #1487 #1329 #1304 #1294 #793 Consul polling of services: enhancements and fix errors
  docs/features/servicediscovery.rst
  src/Ocelot.Provider.Consul/Consul.cs
  src/Ocelot.Provider.Consul/ConsulClientFactory.cs
  src/Ocelot.Provider.Consul/ConsulFileConfigurationRepository.cs
  src/Ocelot.Provider.Consul/ConsulMiddlewareConfigurationProvider.cs
  src/Ocelot.Provider.Consul/ConsulProviderFactory.cs
  src/Ocelot.Provider.Consul/ConsulRegistryConfiguration.cs
  src/Ocelot.Provider.Consul/IConsulClientFactory.cs
  src/Ocelot.Provider.Consul/OcelotBuilderExtensions.cs
  src/Ocelot.Provider.Consul/PollConsul.cs
  src/Ocelot.Provider.Consul/UnableToSetConfigInConsulError.cs
  src/Ocelot.Provider.Consul/Usings.cs
  src/Ocelot.Provider.Eureka/Eureka.cs
  src/Ocelot.Provider.Eureka/EurekaProviderFactory.cs
  src/Ocelot.Provider.Kubernetes/KubernetesProviderFactory.cs
  src/Ocelot.Provider.Kubernetes/PollKube.cs
  src/Ocelot/ServiceDiscovery/ServiceDiscoveryProviderFactory.cs
  test/Ocelot.AcceptanceTests/SequentialTestsCollection.cs
  test/Ocelot.UnitTests/Consul/PollingConsulServiceDiscoveryProviderTests.cs
  test/Ocelot.UnitTests/Consul/ProviderFactoryTests.cs
  test/Ocelot.UnitTests/Kubernetes/PollingKubeServiceDiscoveryProviderTests.cs
  test/Ocelot.UnitTests/ServiceDiscovery/ServiceDiscoveryProviderFactoryTests.cs
Labels: bug, enhancement, needs feedback

#1505 Ignore port when using UpstreamHost option
  src/Ocelot/DownstreamRouteFinder/Middleware/DownstreamRouteFinderMiddleware.cs
Labels: bug, proposal, needs feedback, waiting

#1399 #1400 Manage multiple patterns for allowed/blocked IPs via Security Options config section
  docs/features/configuration.rst
  docs/features/routing.rst
  src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs
  src/Ocelot/Configuration/File/FileSecurityOptions.cs
  src/Ocelot/Configuration/SecurityOptions.cs
  src/Ocelot/Ocelot.csproj
  test/Ocelot.UnitTests/Security/IPSecurityPolicyTests.cs
Labels: enhancement, accepted

#1424 Second parameter of Substring is wrong in HeaderFindAndReplaceCreator
  src/Ocelot/Configuration/Creator/HeaderFindAndReplaceCreator.cs
  test/Ocelot.UnitTests/Configuration/HeaderFindAndReplaceCreatorTests.cs
Labels: bug, needs feedback

#1334 #653 Adding null check for downstreamResponse
  src/Ocelot/Responder/Middleware/ResponderMiddleware.cs
  test/Ocelot.AcceptanceTests/CustomMiddlewareTests.cs
  test/Ocelot.UnitTests/Responder/ResponderMiddlewareTests.cs
Labels: bug, needs feedback
