Repository ThreeMammals/Ocelot, pull requests merged in 2024-02, with the labels that each got.

#1870 #740 #1580 Support multiple authentication schemes in one route
  docs/features/authentication.rst
  src/Ocelot/Authentication/Middleware/AuthenticationMiddleware.cs
  src/Ocelot/Authentication/Middleware/AuthenticationMiddlewareExtensions.cs
  src/Ocelot/Authentication/Middleware/AuthenticationMiddlewareMiddlewareExtensions.cs
  src/Ocelot/Configuration/AuthenticationOptions.cs
  src/Ocelot/Configuration/Builder/AuthenticationOptionsBuilder.cs
  src/Ocelot/Configuration/Creator/AuthenticationOptionsCreator.cs
  src/Ocelot/Configuration/Creator/RouteOptionsCreator.cs
  src/Ocelot/Configuration/File/FileAuthenticationOptions.cs
  src/Ocelot/Configuration/Validator/FileConfigurationFluentValidator.cs
  src/Ocelot/Configuration/Validator/RouteFluentValidator.cs
  src/Ocelot/Values/DownstreamPathTemplate.cs
  test/Ocelot.AcceptanceTests/Authentication/AuthenticationSteps.cs
  test/Ocelot.AcceptanceTests/Authentication/AuthenticationTests.cs
  test/Ocelot.AcceptanceTests/Authentication/MultipleAuthSchemesFeatureTests.cs
  test/Ocelot.AcceptanceTests/AuthenticationTests.cs
  test/Ocelot.AcceptanceTests/AuthorizationTests.cs
  test/Ocelot.AcceptanceTests/PollyQoSTests.cs
  test/Ocelot.AcceptanceTests/Steps.cs
  test/Ocelot.UnitTests/Authentication/AuthenticationMiddlewareTests.cs
  test/Ocelot.UnitTests/Configuration/AuthenticationOptionsCreatorTests.cs
  test/Ocelot.UnitTests/Configuration/RouteOptionsCreatorTests.cs
  test/Ocelot.UnitTests/Configuration/Validation/FileConfigurationFluentValidatorTests.cs
  test/Ocelot.UnitTests/Configuration/Validation/RouteFluentValidatorTests.cs
  test/Ocelot.UnitTests/Polly/PollyQoSProviderTests.cs
Labels: feature, Nov'23

#1962 Release 23.0 | Artifacts | +semver: breaking
  ReleaseNotes.md
  docs/conf.py
  docs/features/authentication.rst
  docs/features/caching.rst
  docs/features/kubernetes.rst
  docs/features/routing.rst
  docs/features/servicediscovery.rst
  docs/index.rst
  docs/introduction/gotchas.rst
Labels: release, Nov'23

#1963 Sync 'develop' to 'release/23.0'
  ReleaseNotes.md
  docs/conf.py
  docs/features/authentication.rst
  docs/features/caching.rst
  docs/features/kubernetes.rst
  docs/features/routing.rst
  docs/features/servicediscovery.rst
  docs/index.rst
  docs/introduction/gotchas.rst
Labels: gitflow, Nov'23

#1462 #1396 Lost context `User` in `MultiplexingMiddleware`
  src/Ocelot/Multiplexer/MultiplexingMiddleware.cs
  test/Ocelot.AcceptanceTests/AggregateTests.cs
  test/Ocelot.AcceptanceTests/Authentication/AuthenticationTests.cs
  test/Ocelot.AcceptanceTests/Steps.cs
  test/Ocelot.UnitTests/Multiplexing/MultiplexingMiddlewareTests.cs
Labels: bug, proposal, Aggregation, high, Jan'24

#1845 #1844 More open customization of Polly use
  src/Ocelot.Provider.Polly/OcelotBuilderExtensions.cs
Labels: feature, small effort, proposal, high, Jan'24

#1974 #1844 More open customization of Polly use
  src/Ocelot.Provider.Polly/OcelotBuilderExtensions.cs
Labels: feature, small effort, Jan'24

#1953 Logging bug in `HttpRequesterMiddleware`
  src/Ocelot/Requester/Middleware/HttpRequesterMiddleware.cs
  test/Ocelot.UnitTests/Requester/HttpRequesterMiddlewareTests.cs
Labels: bug, Jan'24

#1944 #849 #1496 Extend the route key format used for load balancing making it unique
  src/Ocelot/Configuration/Creator/RouteKeyCreator.cs
  src/Ocelot/LoadBalancer/LoadBalancers/LoadBalancerHouse.cs
  test/Ocelot.AcceptanceTests/ServiceDiscoveryTests.cs
  test/Ocelot.AcceptanceTests/Steps.cs
  test/Ocelot.UnitTests/Configuration/RouteKeyCreatorTests.cs
Labels: bug, Service Discovery, Load Balancer, Jan'24

#1972 #1971 #928 Avoid content if original request has no content and avoid Transfer-Encoding: chunked if Content-Length is known
  src/Ocelot/Request/Mapper/RequestMapper.cs
  src/Ocelot/Request/Mapper/StreamHttpContent.cs
  test/Ocelot.AcceptanceTests/HttpTests.cs
  test/Ocelot.AcceptanceTests/Request/RequestMapperTests.cs
  test/Ocelot.AcceptanceTests/Request/StreamContentTests.cs
  test/Ocelot.AcceptanceTests/ServiceHandler.cs
  test/Ocelot.AcceptanceTests/Steps.cs
  test/Ocelot.UnitTests/Request/Mapper/RequestMapperTests.cs
Labels: bug, Jan'24, Routing
